/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GymActivity = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Text,
  'description' : IDL.Text,
  'muscleGroups' : IDL.Text,
  'estimatedCalories' : IDL.Nat,
});
export const NutritionEntry = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Text,
  'description' : IDL.Text,
  'sugar' : IDL.Text,
  'estimatedCalories' : IDL.Nat,
  'protein' : IDL.Text,
});
export const StudyTopic = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'timeTargetMinutes' : IDL.Nat,
  'subject' : IDL.Text,
  'createdAt' : IDL.Text,
  'topicName' : IDL.Text,
});
export const DailyGoals = IDL.Record({
  'nmbDone' : IDL.Bool,
  'sleepDone' : IDL.Bool,
  'schoolDone' : IDL.Bool,
});
export const MeasurementRecord = IDL.Record({
  'weeklyMeasurementDate' : IDL.Text,
  'monthlyMeasurementDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGymActivity' : IDL.Func([IDL.Text, IDL.Text, GymActivity], [], []),
  'addNutritionEntry' : IDL.Func([IDL.Text, IDL.Text, NutritionEntry], [], []),
  'addStudyTopic' : IDL.Func([IDL.Text, IDL.Text, StudyTopic], [], []),
  'getDailyGoals' : IDL.Func([IDL.Text, IDL.Text], [DailyGoals], ['query']),
  'getGymActivities' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(GymActivity)],
      ['query'],
    ),
  'getMeasurements' : IDL.Func([IDL.Text], [MeasurementRecord], ['query']),
  'getNutritionEntries' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(NutritionEntry)],
      ['query'],
    ),
  'getStreak' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getStudyTopics' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(StudyTopic)],
      ['query'],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'updateDailyGoals' : IDL.Func([IDL.Text, IDL.Text, DailyGoals], [], []),
  'updateMeasurements' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateStreak' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GymActivity = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Text,
    'description' : IDL.Text,
    'muscleGroups' : IDL.Text,
    'estimatedCalories' : IDL.Nat,
  });
  const NutritionEntry = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Text,
    'description' : IDL.Text,
    'sugar' : IDL.Text,
    'estimatedCalories' : IDL.Nat,
    'protein' : IDL.Text,
  });
  const StudyTopic = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'timeTargetMinutes' : IDL.Nat,
    'subject' : IDL.Text,
    'createdAt' : IDL.Text,
    'topicName' : IDL.Text,
  });
  const DailyGoals = IDL.Record({
    'nmbDone' : IDL.Bool,
    'sleepDone' : IDL.Bool,
    'schoolDone' : IDL.Bool,
  });
  const MeasurementRecord = IDL.Record({
    'weeklyMeasurementDate' : IDL.Text,
    'monthlyMeasurementDate' : IDL.Text,
  });
  
  return IDL.Service({
    'addGymActivity' : IDL.Func([IDL.Text, IDL.Text, GymActivity], [], []),
    'addNutritionEntry' : IDL.Func(
        [IDL.Text, IDL.Text, NutritionEntry],
        [],
        [],
      ),
    'addStudyTopic' : IDL.Func([IDL.Text, IDL.Text, StudyTopic], [], []),
    'getDailyGoals' : IDL.Func([IDL.Text, IDL.Text], [DailyGoals], ['query']),
    'getGymActivities' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(GymActivity)],
        ['query'],
      ),
    'getMeasurements' : IDL.Func([IDL.Text], [MeasurementRecord], ['query']),
    'getNutritionEntries' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(NutritionEntry)],
        ['query'],
      ),
    'getStreak' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getStudyTopics' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(StudyTopic)],
        ['query'],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'updateDailyGoals' : IDL.Func([IDL.Text, IDL.Text, DailyGoals], [], []),
    'updateMeasurements' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateStreak' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };