/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyGoals {
  'nmbDone' : boolean,
  'sleepDone' : boolean,
  'schoolDone' : boolean,
}
export interface GymActivity {
  'id' : string,
  'createdAt' : string,
  'description' : string,
  'muscleGroups' : string,
  'estimatedCalories' : bigint,
}
export interface MeasurementRecord {
  'weeklyMeasurementDate' : string,
  'monthlyMeasurementDate' : string,
}
export interface NutritionEntry {
  'id' : string,
  'createdAt' : string,
  'description' : string,
  'sugar' : string,
  'estimatedCalories' : bigint,
  'protein' : string,
}
export interface StudyTopic {
  'id' : string,
  'status' : string,
  'timeTargetMinutes' : bigint,
  'subject' : string,
  'createdAt' : string,
  'topicName' : string,
}
export interface _SERVICE {
  'addGymActivity' : ActorMethod<[string, string, GymActivity], undefined>,
  'addNutritionEntry' : ActorMethod<
    [string, string, NutritionEntry],
    undefined
  >,
  'addStudyTopic' : ActorMethod<[string, string, StudyTopic], undefined>,
  'getDailyGoals' : ActorMethod<[string, string], DailyGoals>,
  'getGymActivities' : ActorMethod<[string, string], Array<GymActivity>>,
  'getMeasurements' : ActorMethod<[string], MeasurementRecord>,
  'getNutritionEntries' : ActorMethod<[string, string], Array<NutritionEntry>>,
  'getStreak' : ActorMethod<[string], bigint>,
  'getStudyTopics' : ActorMethod<[string, string], Array<StudyTopic>>,
  'login' : ActorMethod<[string, string], string>,
  'register' : ActorMethod<[string, string, string], string>,
  'updateDailyGoals' : ActorMethod<[string, string, DailyGoals], undefined>,
  'updateMeasurements' : ActorMethod<[string, string, string], undefined>,
  'updateStreak' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];